### PR TITLE
diamond support

### PR DESCRIPTION
**Pull request by Hackzzila**
Following up on our conversation via email I have added diamond support. 

To publish the package when you are ready, run the following commands:
Install diamond:
`npm i -g diamondpkg` 

Register for an account:
`diamond login`

Publish the package (run in package dir)
`diamond publish`

### CODE REVIEW

**Comment by Hackzzila** [comment]
I would not advise to merge this right now. As pointed out by another diamond user I will add support to pull package info directly from a package.json file for packages that don't use any of diamond's advanced features. This should not take more than a day.

**Comment by Hackzzila** [comment]
On diamond v0.10.1, package info can be gathered from a `package.json` file if no `diamond.json` file is found. You can now run the above steps and not have to edit a `diamond.json` for stuff like new versions.

**Comment by LukyVj** [comment]
Hello, could you fix the conflict before in order for me to merge it. Thanks.

**Comment by TheJaredWilcurt** [comment]
This PR can be closed. The Diamond project was abandoned in 2017 and their website is no longer up.

**Pull request closed without merging**
